services:
  mysql:
    image: 'mysql:8.4'
    restart: unless-stopped
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
        MYSQL_DATABASE: 'shab'
        MYSQL_USER: 'shab'
        MYSQL_PASSWORD: 'shab'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    container_name: minio
    ports:
      - '9000:9000' # API
      - '8900:8900' # UI
    environment:
      MINIO_ROOT_USER: '${MINIO_USER}'
      MINIO_ROOT_PASSWORD: '${MINIO_PASSWORD}'
    command: minio server /data/minio --console-address ":8900"
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '1025:1025' # SMTP
      - '8025:8025' # UI
